server: 
  port: 9527
 
spring: 
  application:
    name: zuul
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: zuul9527
    prefer-ip-address: true

zuul:
  #ignored-services: microservicecloud-dept
#  prefix: /atguigu
#  ignored-services: "*"
  routes:
#    mydept.serviceId: microservicecloud-dept #微服务名称
#    mydept.path: /mydept/**  #映射路径
 
info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

