server:
  port: 8001
spring:
  application:
    name: AppServer
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: app-8001
    prefer-ip-address: true
info:
  app.name: com.jzfb.app
  company.name: www.app.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

